import { Geist, Geist_Mono } from "next/font/google";
import { dark } from '@clerk/themes'
import "./globals.css";
import {
  ClerkProvider,
  // SignInButton,
  // SignUpButton,
  // SignedIn,
  // SignedOut,
  // UserButton,
} from '@clerk/nextjs'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark,
    }}
    >
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <header className="flex justify-end items-center p-2 mt-1 gap-4 h-12 ">
          <SignedOut>
            <SignInButton>
              <Button className='bg-black px-4 py-3 rounded-full'>Sign In</Button>
            </SignInButton>
            <SignUpButton>
            <Button className='bg-black px-4 py-3 rounded-full'>Sign Up</Button>
            </SignUpButton>
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </header> */}
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
