// import { Geist, Geist_Mono } from "next/font/google";
import { dark } from '@clerk/themes'
import "./globals.css";
import {
  ClerkProvider,
  // SignInButton,
  // SignUpButton,
  // SignedIn,
  // SignedOut,
  // UserButton,
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner";


import { Exo_2 } from "next/font/google";

const exo2 = Exo_2({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});


export const metadata = {
  title: "Mock-IQ : Your Personal Interview Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark,
    }}
    >
    <html lang="en">
      <body className={exo2.className}>
       <Toaster/>
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
